#!/usr/bin/env node
import { Command } from "commander"; import fs from "node:fs/promises"; import { findSessions, chooseLatest } from "./scanners/findSessions.js"; import { parseClaudeSession } from "./providers/claude.js"; import { parseCodexSession } from "./providers/codex.js"; import { parsePiSession } from "./providers/pi.js"; import { renderReplay } from "./render/renderReplay.js"; import { openBrowser } from "./utils/openBrowser.js"; import { buildGitReplay } from "./git/gitReplay.js"; import { installHooks, appendHook } from "./hooks/installHooks.js"; import { Provider } from "./providers/types.js";
const program=new Command(); program.name("villani-flight-recorder").description("Black box recorder for AI coding agents").version("0.1.0");
program.command("scan").option("--provider <provider>").option("--root <path>","scan a test/custom root").action(async(o)=>{ const sessions=await findSessions({provider:o.provider, roots:o.root?[o.root]:undefined}); for(const s of sessions) console.log(`${s.provider}\n  path: ${s.path}\n  modified: ${new Date(s.mtimeMs).toISOString()}\n  size: ${s.size}\n  cwd: ${s.cwd??"unknown"}\n  session: ${s.sessionId??"unknown"}\n  events: ${s.eventCount??"unknown"}\n`); });
async function parse(provider:Provider,file:string){ if(provider==="claude") return parseClaudeSession(file); if(provider==="codex") return parseCodexSession(file); if(provider==="pi") return parsePiSession(file); const c=await parseClaudeSession(file); c.provider="unknown"; return c; }
program.command("replay").option("--latest").option("--open").option("--provider <provider>").option("--session <path>").option("--no-redact").option("--redact").action(async(o)=>{ if(!o.latest&&!o.session){ console.error("replay requires --latest or --session <path>"); process.exit(2);} let session; if(o.session){ session=await parse((o.provider??"unknown") as Provider,o.session); } else { const sessions=await findSessions({provider:o.provider}); const picked=chooseLatest(sessions); if(!picked.candidate){ console.error("No supported sessions found."); process.exit(1);} if(picked.uncertain) console.warn("Warning: repo matching was uncertain; selected most recently modified session."); session=await parse(picked.candidate.provider,picked.candidate.path); } const file=await renderReplay(session,{redact:o.redact!==false}); console.log(file); if(o.open) openBrowser(file); });
program.command("git-replay").requiredOption("--from <ref>").requiredOption("--to <ref>").option("--open").option("--no-redact").action(async(o)=>{ const s=await buildGitReplay(o.from,o.to); const file=await renderReplay(s,{redact:o.redact!==false}); console.log(file); if(o.open) openBrowser(file); });
program.command("install-hooks").action(async()=>console.log(`Wrote ${await installHooks()}`));
program.command("hook").argument("<provider>").action(async(provider)=>{ let data=""; process.stdin.setEncoding("utf8"); for await (const c of process.stdin) data+=c; let payload:unknown=data; try{payload=JSON.parse(data)}catch{} await appendHook(provider,payload); });
program.parseAsync().catch(e=>{console.error(e instanceof Error?e.message:String(e)); process.exit(1);});
